### ISSUE TITLE
Extensions question

### ISSUE THREAD

**Issue by l-ko** [PeculiarVentures/pkijs-es6#37]
Why Certificate instance has an 'extensions' property which is an array of Extension, while CRL has a 'crlExtensions' property which is an instance of Extensions?
```
Certificate {
  extensions: [Extension {}, Extension {}]
}
CRL {
  crlExtensions: Extensions {
    extensions: [Extension {}, Extension {}]
  }
}
RevokedCertificate {
  crlEntryExtensions: Extensions {
    extensions: [Extension {}, Extension {}]
  }
}
```

**Comment by YuryStrozhevsky** [comment]
This was done because usually all PKI objects use "Extensions" (set of "Extension") and writing in ASN.1 schema every time "SEQUENCE {Extension}" could lead to possible mistakes. 

There is a way in ES6 how to expose internal array to a "head object". Probably I will apply the trick since seems that having "Extensions" object is obvious in some cases.
